/* Offline copy: the first visit over https (or localhost) saves every file of the app on the device; after that it opens with no
   network. cfa-l2-c37724bbb8 and ["./", ".nojekyll", "README.md", "app.html", "cases.html", "index.html", "manifest.webmanifest", "static/data/casedata.js", "static/data/glossary.js", "static/data/guide-narratives.js", "static/data/los-cards.js", "static/data/mapdata.js", "static/data/study-path.js", "static/icon-180.png", "static/icon-192.png", "static/icon-512.png", "static/katex/contrib/auto-render.min.js", "static/katex/fonts/KaTeX_AMS-Regular.woff", "static/katex/fonts/KaTeX_AMS-Regular.woff2", "static/katex/fonts/KaTeX_Caligraphic-Bold.woff", "static/katex/fonts/KaTeX_Caligraphic-Bold.woff2", "static/katex/fonts/KaTeX_Caligraphic-Regular.woff", "static/katex/fonts/KaTeX_Caligraphic-Regular.woff2", "static/katex/fonts/KaTeX_Fraktur-Bold.woff", "static/katex/fonts/KaTeX_Fraktur-Bold.woff2", "static/katex/fonts/KaTeX_Fraktur-Regular.woff", "static/katex/fonts/KaTeX_Fraktur-Regular.woff2", "static/katex/fonts/KaTeX_Main-Bold.woff", "static/katex/fonts/KaTeX_Main-Bold.woff2", "static/katex/fonts/KaTeX_Main-BoldItalic.woff", "static/katex/fonts/KaTeX_Main-BoldItalic.woff2", "static/katex/fonts/KaTeX_Main-Italic.woff", "static/katex/fonts/KaTeX_Main-Italic.woff2", "static/katex/fonts/KaTeX_Main-Regular.woff", "static/katex/fonts/KaTeX_Main-Regular.woff2", "static/katex/fonts/KaTeX_Math-BoldItalic.woff", "static/katex/fonts/KaTeX_Math-BoldItalic.woff2", "static/katex/fonts/KaTeX_Math-Italic.woff", "static/katex/fonts/KaTeX_Math-Italic.woff2", "static/katex/fonts/KaTeX_SansSerif-Bold.woff", "static/katex/fonts/KaTeX_SansSerif-Bold.woff2", "static/katex/fonts/KaTeX_SansSerif-Italic.woff", "static/katex/fonts/KaTeX_SansSerif-Italic.woff2", "static/katex/fonts/KaTeX_SansSerif-Regular.woff", "static/katex/fonts/KaTeX_SansSerif-Regular.woff2", "static/katex/fonts/KaTeX_Script-Regular.woff", "static/katex/fonts/KaTeX_Script-Regular.woff2", "static/katex/fonts/KaTeX_Size1-Regular.woff", "static/katex/fonts/KaTeX_Size1-Regular.woff2", "static/katex/fonts/KaTeX_Size2-Regular.woff", "static/katex/fonts/KaTeX_Size2-Regular.woff2", "static/katex/fonts/KaTeX_Size3-Regular.woff", "static/katex/fonts/KaTeX_Size3-Regular.woff2", "static/katex/fonts/KaTeX_Size4-Regular.woff", "static/katex/fonts/KaTeX_Size4-Regular.woff2", "static/katex/fonts/KaTeX_Typewriter-Regular.woff", "static/katex/fonts/KaTeX_Typewriter-Regular.woff2", "static/katex/katex.min.css", "static/katex/katex.min.js", "static/lock-config.js", "static/lock.js", "static/los.js", "static/path.css", "static/path.js", "static/profile.js", "static/site.css", "static/standalone.js"] are filled in by build_standalone.py, so a new build replaces the old copy. */
const VERSION = "cfa-l2-c37724bbb8";
const FILES = ["./", ".nojekyll", "README.md", "app.html", "cases.html", "index.html", "manifest.webmanifest", "static/data/casedata.js", "static/data/glossary.js", "static/data/guide-narratives.js", "static/data/los-cards.js", "static/data/mapdata.js", "static/data/study-path.js", "static/icon-180.png", "static/icon-192.png", "static/icon-512.png", "static/katex/contrib/auto-render.min.js", "static/katex/fonts/KaTeX_AMS-Regular.woff", "static/katex/fonts/KaTeX_AMS-Regular.woff2", "static/katex/fonts/KaTeX_Caligraphic-Bold.woff", "static/katex/fonts/KaTeX_Caligraphic-Bold.woff2", "static/katex/fonts/KaTeX_Caligraphic-Regular.woff", "static/katex/fonts/KaTeX_Caligraphic-Regular.woff2", "static/katex/fonts/KaTeX_Fraktur-Bold.woff", "static/katex/fonts/KaTeX_Fraktur-Bold.woff2", "static/katex/fonts/KaTeX_Fraktur-Regular.woff", "static/katex/fonts/KaTeX_Fraktur-Regular.woff2", "static/katex/fonts/KaTeX_Main-Bold.woff", "static/katex/fonts/KaTeX_Main-Bold.woff2", "static/katex/fonts/KaTeX_Main-BoldItalic.woff", "static/katex/fonts/KaTeX_Main-BoldItalic.woff2", "static/katex/fonts/KaTeX_Main-Italic.woff", "static/katex/fonts/KaTeX_Main-Italic.woff2", "static/katex/fonts/KaTeX_Main-Regular.woff", "static/katex/fonts/KaTeX_Main-Regular.woff2", "static/katex/fonts/KaTeX_Math-BoldItalic.woff", "static/katex/fonts/KaTeX_Math-BoldItalic.woff2", "static/katex/fonts/KaTeX_Math-Italic.woff", "static/katex/fonts/KaTeX_Math-Italic.woff2", "static/katex/fonts/KaTeX_SansSerif-Bold.woff", "static/katex/fonts/KaTeX_SansSerif-Bold.woff2", "static/katex/fonts/KaTeX_SansSerif-Italic.woff", "static/katex/fonts/KaTeX_SansSerif-Italic.woff2", "static/katex/fonts/KaTeX_SansSerif-Regular.woff", "static/katex/fonts/KaTeX_SansSerif-Regular.woff2", "static/katex/fonts/KaTeX_Script-Regular.woff", "static/katex/fonts/KaTeX_Script-Regular.woff2", "static/katex/fonts/KaTeX_Size1-Regular.woff", "static/katex/fonts/KaTeX_Size1-Regular.woff2", "static/katex/fonts/KaTeX_Size2-Regular.woff", "static/katex/fonts/KaTeX_Size2-Regular.woff2", "static/katex/fonts/KaTeX_Size3-Regular.woff", "static/katex/fonts/KaTeX_Size3-Regular.woff2", "static/katex/fonts/KaTeX_Size4-Regular.woff", "static/katex/fonts/KaTeX_Size4-Regular.woff2", "static/katex/fonts/KaTeX_Typewriter-Regular.woff", "static/katex/fonts/KaTeX_Typewriter-Regular.woff2", "static/katex/katex.min.css", "static/katex/katex.min.js", "static/lock-config.js", "static/lock.js", "static/los.js", "static/path.css", "static/path.js", "static/profile.js", "static/site.css", "static/standalone.js"];
self.addEventListener("install", (e) => {
  // "reload" so a new version is fetched from the network, not from the browser's own copy of the old files
  e.waitUntil(caches.open(VERSION).then((c) => Promise.all(FILES.map((f) => c.add(new Request(f, { cache: "reload" }))))).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith("cfa-l2-") && k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  if (e.request.mode === "navigate") {  // pages: the network when there is one (so a new version shows at once), else the saved copy
    e.respondWith(fetch(e.request).catch(() => caches.match(e.request, { ignoreSearch: true })));
    return;
  }
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((r) => r || fetch(e.request)));
});
